local_backend: true

backend:
  #name: git-gateway
  name: proxy
  branch: main
  proxy_url: http://localhost:8081/api/v1

publish_mode: editorial_workflow

media_folder: public/images/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /images/uploads # The src attribute for uploaded media will begin with /images/uploads

collections:

#general

  - name: general
    label: General
    files:
      - label: Logos
        name: logos
        file: "/src/pages/content/assets.md"
        fields: 
          - {label: Header Logo, name: headerLogo, widget: image}
          - {label: Footer Logo, name: footerLogo, widget: image}

      - label: Contact Prompt
        name: contactPrompt
        file: "/src/pages/content/prompt.md"
        fields:
          - {label: Headline, name: headline, widget: string}
          - {label: Text, name: text, widget: string}
          - label: Custom Request
            name: customRequest
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: string}
      
      - label: Footer Links
        name: footerLinks
        file: "/src/pages/content/links.md"
        fields:
          - label: Footer Link
            name: footerLink
            widget: list
            allow_add: true
            fields: 
              - {label: Text to Display, name: displayText, widget: string} 
              - {label: URL, name: url, widget: string} 

  - name: pages
    label: Pages
    files:  

#home

      - label: Home
        name: home
        file: "/src/pages/content/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Layout, name: layout, widget: hidden, default: ../index.astro*}


          - label: Banner
            name: banner
            widget: object
            fields: 
              - {label: Headline, name: headline, widget: string}
              - {label: Image, name: image, widget: image}
              - label: Info
                name: info 
                widget: list 
                allow_add: true
                field: {label: Item, name: item, widget: string}


          - label: Services
            name: services
            widget: object
            fields: 
              - {label: Heading, name: heading, widget: string}
              - label: Service
                name: service
                widget: list
                allow_add: true
                fields: 
                  - {label: Item, name: item, widget: string}
                  - {label: Description, name: description, widget: string}


          - label: Comparison Chart
            name: comparisonChart
            widget: object
            fields: 
              - {label: Heading, name: heading, widget: string}
              - label: Item
                name: item
                widget: list
                allow_add: true
                fields: 
                  - label: Work Type
                    name: workType
                    widget: object
                    fields: 
                      - {label: Heading, name: heading, widget: string}
                      - label: Item
                        name: item
                        widget: list
                        allow_add: true
                        fields: 
                          - label: item
                            name: item
                            widget: object
                            fields: 
                              - {label: Text, name: text, widget: string}
                              - {label: "Tick", name: "tick", widget: "boolean", default: false}

#services         

      - name: services
        label: Services
        file: "/src/pages/content/services.md"
        fields: 
          - {label: hello, name: hello, widget: string}




      
